# Two Special Functions

- np.diff()
- np.cumdiff()

In [14]:
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import numpy as np
import scipy.stats as stats
from scipy.stats import gaussian_kde

## Read in a CSV data file from the web.
july = Table.read_table('JulyTemps_GrandCanyon.csv')

## Data Set: July Weather at the Grand Canyon

The table **july** we imported above has high and low temperatures and precipitation amounts for the Grand Canyon in 2025.

In [20]:
low = july.column("Low_TempDegrees")
hi =  july.column("Hi_TempDegrees")
precip =  july.column("Precip (inches)")
july

Day,Hi_TempDegrees,Low_TempDegrees,Precip (inches)
1,79,12,0
2,82,15,0
3,85,16,0
4,87,7,0
5,88,14,0
6,89,31,0
7,93,31,0
8,92,33,0
9,92,27,0
10,93,22,0


## np.diff

The function **np.diff()** finds the successive differences between items in the array. Let's try an example to see how it works.

In [16]:
low

array([12, 15, 16,  7, 14, 31, 31, 33, 27, 22, 20, 32, 38, 44, 51, 52, 56,
       56, 53, 51, 53, 50, 51, 49, 42, 47, 49, 52, 50, 45, 36])

In [17]:
np.diff(low)

array([ 3,  1, -9,  7, 17,  0,  2, -6, -5, -2, 12,  6,  6,  7,  1,  4,  0,
       -3, -2,  2, -3,  1, -2, -7,  5,  2,  3, -2, -5, -9])

## np.cumsum

The function **np.cumsum()** finds the sum from the first element to the current element.The final element will have the sum of all elements in the array.

In [18]:
precip

array([ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.35,  0.01,  0.17,  0.12,  0.  ,  0.45,  0.22,
        1.86,  0.  ,  0.68,  0.  ,  0.89,  0.  ,  0.  ,  0.02,  0.  ,
        0.04,  0.  ,  0.  ,  0.  ])

In [19]:
np.cumsum(precip)

array([ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.35,  0.36,  0.53,  0.65,  0.65,  1.1 ,  1.32,
        3.18,  3.18,  3.86,  3.86,  4.75,  4.75,  4.75,  4.77,  4.77,
        4.81,  4.81,  4.81,  4.81])