# <span style="color:blue; font-size:1.1em">Day 4: Arrays and Tables</span>
In this notebook we will:
    
- Review the most important **table methods**.
- Review **arrays** and how arrays work with functions.
- Learn that table **columns** contain **array data** and how to covert them to arrays.
- How to **add a column to a table**.

In [1]:
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import numpy as np
import seaborn as sns
import scipy.stats as stats
from scipy.stats import gaussian_kde

## Read in a CSV data file from the web.
skyscrapers = Table.read_table('skyscrapers.csv')
pers = Table.read_table('http://faculty.ung.edu/rsinn/personality.csv')
births = Table.read_table('https://faculty.ung.edu/rsinn/data/baby.csv')

## The <span style=color:blue;font-size:1.1em>Key 5</span> Table Methods
We use the following table methods in nearly every learning notebook for the semester:

- **.sort**
- **.select**
- **.show**
- **.where**
- <span style=color:blue;font-weight:bold;font-size:1.1em>.column</span>

We have not yet learned to use <span style=color:blue;font-weight:bold;font-size:1.1em>.column</span>, but let's practice the other four with the questions that follow.

### Practice Question: Display the **skyscrapers** table with only columns 'name' and 'height'.

### Practice Question: Do the same probelm as above, but use **.drop** instead of **.select**.

### Practice Question: Find all the Chicago skyscrapers in the table.

In [31]:
chicago = ...

### Practice Question: Display the newest five Chicago skyscrapers.

In [32]:
new_chicago = ...

## <span style="color:blue; font-size:1.1em; font-weight:bold">1. Arrays</span>
The easiest way to create an array is to use the<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">make_array()</span></center></br>function. Let create a couple of arrays and see why we like this data type.

In [33]:
my_array = make_array(1, 2, 3, 4)
my_array

array([1, 2, 3, 4])

In [34]:
another = make_array(60, 70, 80, 90)
another

array([60, 70, 80, 90])

### Practice Question: Do the following calculations.
1. Multiply **my_array** by 2.
2. Raise **my_array** to the 2nd power.
3. Add 1 to **my_array**.

### Practice Question: Can we Add two Arrays?

**Hint:** trying adding **another** to **my_array**.

Note that the arrays must have the same number of elements, or we cannot add them.

## <span style="color:blue; font-size:1.1em; font-weight:bold">2. Function and Arrays</span>
The array arithmetic needed for <span style="color:red; font-weight:bold; font-size: 1.1em"> exploratory data analysis</span> can often be sped up using functions to calcuate the mean, standard deviation, or sample size.

- For **sample size**, use the function **len()**.
- For **average**, we can use **np.average()**.
- For **median**, we can use **np.median()**.
- For **standard deviation**, we can use **stats.tstd()**

In [35]:
sum(my_array)/len(my_array)

2.5

In [36]:
# Find the average of my_array using the np.average() function.
avg = ...

### The data set $N$ represents daily high temperatures in Dahlonega, GA, for the month of November. 

In [37]:
N = make_array(67, 65, 66, 63, 60, 62, 64, 68, 71, 69, 65, 62, 59, 58, 61,
               63, 66, 62, 59, 57, 55, 58, 60, 63, 62, 58, 56, 54, 57, 59)

### <span style=font-weight:bold;font-size:1.1em>Find the summary statistics of $N$</span> 

In [38]:
avg = ...

In [39]:
stdev = ...

In [40]:
sample_size = ...

The **standard descriptives** are shown above and include:
- Mean ( $\bar x$ )
- Standard Deviation ( $s$ )
- Sample Size ( $n$ )

The **5-Number Summary** is shown below and includes:
- Min
- Q1 (25th percentile)
- Median
- Q3 (75th percentile)
- Max

In [41]:
min = ...

In [42]:
Q1 = ...

In [43]:
median = ...

In [44]:
Q3 = ...

In [45]:
max = ...

##  <span style="color:blue;font-weight:bold; font-size: 1.1em">3. Columns of Tables are Arrays</span>

We often need to extract a column from a table to perform <span style="color:red; font-weight:bold; font-size: 1.1em"> exploratory data analysis</span> calculations. We use the fifth of our Key 5 table methods<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">.column</span></center></br>to perform this extraction. Appending <center><span style="color:darkblue; font-weight:bold; font-size:1.2em">[:5]</span></center></br> to an array displays only the first five items of the array.

### <span style="color:blue;font-weight:bold; font-size: 1.1em">Example</span>

In [46]:
heights = skyscrapers.column('height')
heights[:10]

array([ 541.29998779,  442.14001465,  425.5       ,  423.22000122,
        381.        ,  365.79998779,  350.22000122,  346.26000977,
        343.69000244,  329.        ])

### Practice Question: Create the **sf** <span style="color:red">table</span> of skyscrapers in San Francisco.

In [47]:
sf = ...

### Practice Question: Create the **sf_heights** <span style="color:red">array</span> of the heights of San Francisco skyscrapers.

In [48]:
sf_heights = ...

### Practice Question: Create the **NY** table of skyscrapers in New York City and the **ny_heights** array of their heights.

In [49]:
ny = ...

In [50]:
ny_heights = ...

### Practice Question: Create the **LA** table of skyscrapers in Los Angeles and the **la_heights** array of their heights.

In [51]:
la = ...

In [52]:
la_heights = ...

## Suppose we wish to add a column to the **sf** table.

The heights are in meters, and we wish to add column where the heights are in feet. The conversion we need is that <center><span style="color:darkblue; font-weight:bold; font-size:1.2em">3.28 feet per meter</span></center></br>

### <span style="font-size:1.1em; font-weight:bold">Practice Question: Convert all values in **sf_heights** to meters.</span>

In [54]:
sf_heights_feet = ...

##  <span style="color:blue;font-weight:bold; font-size: 1.1em">4. Adding a Column to a Table</span>

We use the table method<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">.with_column</span></center></br>

with the new column title listed first in quotes and the array data for the column second.

In [55]:
# Uncomment the commands below to display the result.

#sf_heights_feet = 3.28 # sf_heights
#sf_new = sf.with_column("height (ft)", sf_heights_feet)
#sf_new

### Let's Compare it to the Old Table

In [56]:
sf

Ellipsis

### Practice Question: Find the difference in average heights between New York and Los Angeles.

In [57]:
diff = ...

### Practice Question: Determine the number of skyscrapers in the table that are located New York City.

In [58]:
num_ny = ...

### Practice Question: How many skyscrapers in the table are located in Chicago?

In [59]:
num_chi = ...